### ISSUE TITLE
Can I choose which page as first page?

### ISSUE THREAD

**Issue by bobbytung** [hanchang/friar#10]
Hello, 

Very appreciate your work. I'd like to use Friar on Manga work that is from right page to left page.
In Baker Framework, they add value "-baker-start-at-page": -1, in books.json to let as choose which page as first page. could Friar be able to assign last page as start page?

**Comment by webschnecke** [comment]
Hi, you are able to set it with : 

"-baker-start-at-page":4,
"contents": [
"page00.html",
"page01.html",
"page02.html",
"page03.html",
"page04.html",
"page05.html"
]

PageNr 4 = page03.html ;-)

Have fun.
