### ISSUE TITLE
I need some tutorial 

### ISSUE THREAD

**Issue by molorago** [hanchang/friar#14]
I already work with baker, but i really dont know where to start whit friar, can someone help me???
Some tutorial or something
i will really apreciate it

thanks

**Comment by hanchang** [comment]
Hi Monica, Friar and Baker are very similar - the only thing you need to do
is set up the development environment for Android on your computer, clone a
copy of the Friar project, and then put your Baker book into the
assets/book/ directory in the Friar project.

For more info on setting up your Android development environment:
http://developer.android.com/training/index.html

For more info on setting up an HPub formatted book:
http://bakerframework.com/tutorials/30/basic

Hope that helps!

**Comment by molorago** [comment]
Hangchang thanks a lot, i already do my app for iphone and ipad, but i never work with android, so i dont know how to install the android development environment... 
There are any tutorial our video to help me?
thanks a lot
