### ISSUE TITLE
How to show the index of the book?

### ISSUE THREAD

**Issue by benoitchantre** [hanchang/friar#19]
The book that is included with friar includes an index, how can we display it?

A double tap doesn't work.

Is it a feature that should work in friar?

**Comment by hanchang** [comment]
The double tap to display a navigation menu feature is unique to the Laker Compendium.
http://www.lakercompendium.com/

Unfortunately this isn't compatible with Android that I'm aware of; see https://github.com/hanchang/friar/issues/12 for more details.
