### ISSUE TITLE
Demo book doesn't work

### ISSUE THREAD

**Issue by Kauhanen** [hanchang/friar#2]
Hi! 

I am using Acer's tablet which has Android 3.2.

I installed the demo book app to it and launched it. It gave this kind of error:

File:///android_asset/book/Book%20Cover.html is not found. 

Any idea what causes this....?

**Comment by Kauhanen** [comment]
Actually I think solved why is it. The files cannot have spaces in their name.

**Comment by freedombird** [comment]
i also meet this problem in my NS.
