### ISSUE TITLE
Opening links crashes the app

### ISSUE THREAD

**Issue by ollisulopuisto** [hanchang/friar#3]
I've a simple <a href="http://teos.fi/">link</a> link in my app, but clicking on it immediately crashes the app.

02-22 14:35:57.595: W/dalvikvm(6501): threadid=1: thread exiting with uncaught exception (group=0x401f8560)
02-22 14:35:57.595: E/AndroidRuntime(6501): FATAL EXCEPTION: main
02-22 14:35:57.595: E/AndroidRuntime(6501): java.lang.NullPointerException
02-22 14:35:57.595: E/AndroidRuntime(6501):     at com.friarframework.FriarBook$FriarWebViewClient.onPageStarted(FriarBook.java:185)
02-22 14:35:57.595: E/AndroidRuntime(6501):     at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:264)
02-22 14:35:57.595: E/AndroidRuntime(6501):     at android.os.Handler.dispatchMessage(Handler.java:99)
02-22 14:35:57.595: E/AndroidRuntime(6501):     at android.os.Looper.loop(Looper.java:130)
02-22 14:35:57.595: E/AndroidRuntime(6501):     at android.app.ActivityThread.main(ActivityThread.java:3835)
02-22 14:35:57.595: E/AndroidRuntime(6501):     at java.lang.reflect.Method.invokeNative(Native Method)
02-22 14:35:57.595: E/AndroidRuntime(6501):     at java.lang.reflect.Method.invoke(Method.java:507)
02-22 14:35:57.595: E/AndroidRuntime(6501):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
02-22 14:35:57.595: E/AndroidRuntime(6501):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
02-22 14:35:57.595: E/AndroidRuntime(6501):     at dalvik.system.NativeStart.main(Native Method)

I've added  <uses-permission android:name="android.permission.INTERNET"/> so that shouldn't be the thing.

**Comment by hanchang** [comment]
Bug confirmed! I'll try to have a fix out by the end of this weekend, thanks for letting me know!

**Comment by hanchang** [comment]
Hi Olli, I've pushed a fix, can you take a look and see if it works for you?
