### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by LeoPovoa** [hanchang/friar#6]
Hi, 

I have a button in a book page that execute a JavaScript code (some calculations). I Can't execute the code, the button came HightLight, but the javascript can't execute. I modify this line: webView.getSettings().setJavaScriptEnabled(false); to true. But nothing change. Please Help me !!

Att, Léo.

**Comment by hanchang** [comment]
Hi Leo, I need more information in order to help you.

What's the code snippet you're trying to execute?

What device / emulator are you trying this out on?

What Android version are you using?

On Tue, Apr 3, 2012 at 2:05 AM, Leonardo Póvoa <
reply@reply.github.com

**Comment by LeoPovoa** [comment]
Hi Han, 

I solved the problem. The emulater was the "problem". In a device the javascript function fine. I Modified this lines:

//Configuracao JavaScript
        WebSettings webSettings = webView.getSettings();
        webSettings.setJavaScriptEnabled(true);
        webSettings.setPluginsEnabled(true);
        webSettings.setLoadsImagesAutomatically(true);
        webSettings.setSupportZoom(false);

Thanks for atention !!! Léo Póvoa

**Comment by hanchang** [comment]
Cool, glad you figured it out, would love a link to your Android App once it hits the App Store!
