### ISSUE TITLE
scripts dont run on simulator

### ISSUE THREAD

**Issue by bahmet** [hanchang/friar#8]
hi,
i have been using baker to make colorbook applications for a while. i made couple of apps that currentl published on the app store. i want to make the same for the android platform and found your site. i simply copied my working copy of Book folder to the assets folder on your framework. i am able to see my pages on the simulator however scripts do not work and the canvas can not seen . 
since i have no idea about android platform
is there a limitation for scripts to work.
i am using https://github.com/williammalone/Simple-HTML5-Drawing-App this script for color book and jquery jplayer for the audio.
i would appreciate if you can advice...
thanks

**Comment by hanchang** [comment]
By default I disabled JavaScript for security reasons but people have had problems with it so I'm enabling it by default.

If you download the new version I just committed it will have the correct settings and your color book should work - let me know if there's anything else!

**Comment by bahmet** [comment]
Hi han
Thanks for prompt reply. İ will try tomorrow and ket you know the result

**Comment by bahmet** [comment]
hi @hanchang ,
it works for the coloring book script, however it does not work for the audio part. can you pls advice what is the supported audio format on android. also do you think jquery jplayer is supproted??
thanks...
